server:
  port: 8081
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: 12345678
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "ZSHNrjFGHzvUebjsJ7IE4/F94AGmze7YZY6Ix1WCGO1xA7uYfPd1ALBI4I9Ez+wD"